# Uncomment this line to define a global platform for your project
 platform :ios, '8.0'
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!
target 'BaseFrame' do
  # Pods for BaseFrame
	pod 'AFNetworking', '3.1.0'
	pod 'APParallaxHeader', '0.1.6'
	pod 'BlocksKit', '2.2.5'
	pod 'CommonElement', '0.2.2'
	pod 'DZNEmptyDataSet', '1.8.1'
	pod 'FMDB', '2.6.2'
	pod 'FoldingTabBar','1.1.1'
	pod 'FontAwesome+iOS', '0.1.4'
	pod 'IQKeyboardManager','4.0.8'
	pod 'MBProgressHUD', '1.0.0'
	pod 'MJExtension','3.0.13'
	pod 'MJRefresh','3.1.12'
	pod 'MMMarkdown', '0.5.5'
	pod 'MMProgressHUD','0.3.2'
	pod 'MarqueeLabel', '2.7.8'
	pod 'Masonry', '1.0.1'
	pod 'NYXImagesKit', '2.3'
	pod 'PPiAwesomeButton', '1.5.2'
	pod 'ReactiveCocoa','2.1.2'
	pod 'RegexKitLite', '4.0'
	pod 'SDWebImage', '3.8.1'
	pod 'SVProgressHUD', '2.0.3'
	pod 'TPKeyboardAvoiding', '1.3'
	pod 'TTTAttributedLabel', '2.0.0'
	pod 'UIImage+BlurredFrame', '0.0.4'
	pod 'hpple', '0.2.0'
	pod 'iCarousel','1.8.3'
	pod 'pop','1.0.9'
	pod 'JSPatch','1.1.3'
	pod 'JSPatchPlatform','1.6.6'
	pod 'JSPatch/Extensions'
	pod 'JSPatch/JPCFunction'
	pod 'YYKit','1.0.9'
	pod 'JSONModel','1.7.0'
  target 'BaseFrameTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BaseFrameUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
